Update 01_algoritmas.rst
nmakademija/inf-knyga pull request #7
Opened 2021-11-25 13:54 UTC by RutaGiedryte

Bandom iš naujo. Nesam įsitikinę, kad iki galo supratom, ko prašėt, kai siūlėt pakeisti į do - while ciklą. Jei čia nuvažiavom į lankas, prašysim patikslinimo :DD

2021-11-25 18:20 UTC, vakaras requested changes
Ačiū. Pridėjau komentarų, tikiuosi bus aiškiau ką turėjau omeny.

2021-11-25 18:20 UTC, vakaras commented on source/01_algoritmas.rst
> +              do {
Kodo formatavimui siūlyčiau naudoti automatinį formatavimo įrankį. Dauguma IDE turi tokį integruotą arba galima pasiieškoti tai darančio internetinio įrankio. [Pavyzdžiui](https://www.tutorialspoint.com/online_c_formatter.htm):

```cpp
int i = -1;
do {
    int j = i;
    i++;
    do {
        j++;
        int suma = 0;
        for (int l = i; l <= j; l++) {
            suma += a[l];
        }
        rasta = (suma == k);
    } while (j < n-1 && !rasta);
} while (i < n-1 && !rasta);
```

2021-11-25 18:20 UTC, vakaras commented on source/01_algoritmas.rst
>      .. code-block:: cpp
```suggestion
    C++ kodas atitinkantis Pascal:

    .. code-block:: cpp
```

2021-11-25 18:20 UTC, vakaras commented on source/01_algoritmas.rst
```suggestion

  .. tab:: Idiomatinis C++
    Labiau idiomatinis C++ kodas:
    .. code-block:: cpp
      bool rasta = false;
      int atsPr, atsPab;
      for(int i = 0; i < n && !rasta; i++) {
          for(int j = i; j < n && !rasta; j++) {
              int suma = 0;
              for(int k = i; k <= j; k++) {
                  suma += a.at(k);
              }
              if (suma == K) {
                  atsPr = i;
                  atsPab = j;
                  rasta = true;
              }
          }
      }
```

2021-11-25 18:20 UTC, vakaras commented on source/01_algoritmas.rst
> +                      suma += a[l];
Masyvas → vektorius:
```suggestion
                      suma += a.at(l);
```

2021-11-27 16:15 UTC, RutaGiedryte commented on source/01_algoritmas.rst
> +              do {
Kadangi pastaruoju metu laiko nelabai daug turim, gal kada ateity pavyks!

2021-11-27 16:19 UTC, RutaGiedryte commented
Pabandėm sutvarkyt :))

2021-11-27 16:27 UTC, vakaras approved these changes
Ačiū!

2021-11-27 16:27 UTC, merged