Update 03_pirminiai.rst
nmakademija/inf-knyga pull request #8
Opened 2021-11-25 13:59 UTC by RutaGiedryte

2021-11-25 18:29 UTC, vakaras requested changes
Ačiū!

2021-11-25 18:29 UTC, vakaras commented on source/03_pirminiai.rst
>        void rėtis(int n) {
Kadangi Paskalio pavyzdys nėra iškeltas į funkciją, tai būtų gerai, kad ir C++ pavyzdys nebūtų atskiroje funkcijoje:
```suggestion

```

2021-11-27 16:11 UTC, RutaGiedryte commented on source/03_pirminiai.rst
>        void rėtis(int n) {
Pakeitėm.

2021-11-27 16:17 UTC, vakaras approved these changes
Ačiū!

2021-11-27 16:17 UTC, merged